/* Generated By:JavaCC: Do not edit this line. ZqlJJParserConstants.java */
package org.gibello.zql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ZqlJJParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 5;
  /** RegularExpression Id. */
  int K_AND = 6;
  /** RegularExpression Id. */
  int K_ANY = 7;
  /** RegularExpression Id. */
  int K_AS = 8;
  /** RegularExpression Id. */
  int K_ASC = 9;
  /** RegularExpression Id. */
  int K_AVG = 10;
  /** RegularExpression Id. */
  int K_BETWEEN = 11;
  /** RegularExpression Id. */
  int K_BINARY_INTEGER = 12;
  /** RegularExpression Id. */
  int K_BOOLEAN = 13;
  /** RegularExpression Id. */
  int K_BY = 14;
  /** RegularExpression Id. */
  int K_CHAR = 15;
  /** RegularExpression Id. */
  int K_COMMENT = 16;
  /** RegularExpression Id. */
  int K_COMMIT = 17;
  /** RegularExpression Id. */
  int K_CONNECT = 18;
  /** RegularExpression Id. */
  int K_COUNT = 19;
  /** RegularExpression Id. */
  int K_DATE = 20;
  /** RegularExpression Id. */
  int K_DELETE = 21;
  /** RegularExpression Id. */
  int K_DESC = 22;
  /** RegularExpression Id. */
  int K_DISTINCT = 23;
  /** RegularExpression Id. */
  int K_DROP = 24;
  /** RegularExpression Id. */
  int K_EXCLUSIVE = 25;
  /** RegularExpression Id. */
  int K_EXISTS = 26;
  /** RegularExpression Id. */
  int K_EXIT = 27;
  /** RegularExpression Id. */
  int K_LISTTABLES = 28;
  /** RegularExpression Id. */
  int K_FLOAT = 29;
  /** RegularExpression Id. */
  int K_FOR = 30;
  /** RegularExpression Id. */
  int K_FROM = 31;
  /** RegularExpression Id. */
  int K_GROUP = 32;
  /** RegularExpression Id. */
  int K_HAVING = 33;
  /** RegularExpression Id. */
  int K_IN = 34;
  /** RegularExpression Id. */
  int K_CONTAINS = 35;
  /** RegularExpression Id. */
  int K_INSERT = 36;
  /** RegularExpression Id. */
  int K_INTEGER = 37;
  /** RegularExpression Id. */
  int K_INTERSECT = 38;
  /** RegularExpression Id. */
  int K_INTO = 39;
  /** RegularExpression Id. */
  int K_IS = 40;
  /** RegularExpression Id. */
  int K_LIKE = 41;
  /** RegularExpression Id. */
  int K_LIMIT = 42;
  /** RegularExpression Id. */
  int K_LOAD = 43;
  /** RegularExpression Id. */
  int K_LOCK = 44;
  /** RegularExpression Id. */
  int K_UNLOCK = 45;
  /** RegularExpression Id. */
  int K_MAX = 46;
  /** RegularExpression Id. */
  int K_MIN = 47;
  /** RegularExpression Id. */
  int K_MINUS = 48;
  /** RegularExpression Id. */
  int K_MODE = 49;
  /** RegularExpression Id. */
  int K_NATURAL = 50;
  /** RegularExpression Id. */
  int K_NOT = 51;
  /** RegularExpression Id. */
  int K_NOWAIT = 52;
  /** RegularExpression Id. */
  int K_NULL = 53;
  /** RegularExpression Id. */
  int K_NUMBER = 54;
  /** RegularExpression Id. */
  int K_OF = 55;
  /** RegularExpression Id. */
  int K_OFFSET = 56;
  /** RegularExpression Id. */
  int K_ONLY = 57;
  /** RegularExpression Id. */
  int K_OR = 58;
  /** RegularExpression Id. */
  int K_ORDER = 59;
  /** RegularExpression Id. */
  int K_PRIOR = 60;
  /** RegularExpression Id. */
  int K_QUIT = 61;
  /** RegularExpression Id. */
  int K_READ = 62;
  /** RegularExpression Id. */
  int K_REAL = 63;
  /** RegularExpression Id. */
  int K_ROLLBACK = 64;
  /** RegularExpression Id. */
  int K_ROW = 65;
  /** RegularExpression Id. */
  int K_SAVE = 66;
  /** RegularExpression Id. */
  int K_SELECT = 67;
  /** RegularExpression Id. */
  int K_SET = 68;
  /** RegularExpression Id. */
  int K_SHARE = 69;
  /** RegularExpression Id. */
  int K_SMALLINT = 70;
  /** RegularExpression Id. */
  int K_START = 71;
  /** RegularExpression Id. */
  int K_SUM = 72;
  /** RegularExpression Id. */
  int K_TABLE = 73;
  /** RegularExpression Id. */
  int K_TRANSACTION = 74;
  /** RegularExpression Id. */
  int K_UNION = 75;
  /** RegularExpression Id. */
  int K_UPDATE = 76;
  /** RegularExpression Id. */
  int K_USE = 77;
  /** RegularExpression Id. */
  int K_VALUES = 78;
  /** RegularExpression Id. */
  int K_VARCHAR2 = 79;
  /** RegularExpression Id. */
  int K_VARCHAR = 80;
  /** RegularExpression Id. */
  int K_WHERE = 81;
  /** RegularExpression Id. */
  int K_WITH = 82;
  /** RegularExpression Id. */
  int K_WORK = 83;
  /** RegularExpression Id. */
  int K_WRITE = 84;
  /** RegularExpression Id. */
  int S_NUMBER = 85;
  /** RegularExpression Id. */
  int FLOAT = 86;
  /** RegularExpression Id. */
  int INTEGER = 87;
  /** RegularExpression Id. */
  int DIGIT = 88;
  /** RegularExpression Id. */
  int LINE_COMMENT = 89;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 90;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 91;
  /** RegularExpression Id. */
  int LETTER = 92;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 93;
  /** RegularExpression Id. */
  int S_BIND = 94;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 95;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 96;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CHAR\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"CONNECT\"",
    "\"COUNT\"",
    "\"DATE\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"LISTTABLES\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IN\"",
    "\"CONTAINS\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LOAD\"",
    "\"LOCK\"",
    "\"UNLOCK\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"MINUS\"",
    "\"MODE\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"PRIOR\"",
    "\"QUIT\"",
    "\"READ\"",
    "\"REAL\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"SAVE\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"START\"",
    "\"SUM\"",
    "\"TABLE\"",
    "\"TRANSACTION\"",
    "\"UNION\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WHERE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\".\"",
    "\"!=\"",
    "\"#\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".*\"",
    "\"?\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
  };

}
